version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  faas-test-1:
    lang: python3-flask
    handler: ./faas-test-1
    image: faas-test-1:v1.0
  faas-test-2:
    lang: python3-flask
    handler: ./faas-test-2
    image: faas-test-2:v1.0